name: hadron
version: 0.3.0
apiVersion: v2
appVersion: 0.1.0
description: Hadron is the Kubernetes native and CloudEvents native distributed event streaming, event orchestration & messaging platform.
