apiVersion: v2
name: hadron-operator
description: Hadron is the Kubernetes native and CloudEvents native distributed event streaming, event orchestration & messaging platform.
type: application
version: 0.1.1
appVersion: 0.1.0-beta.0
