---
kind: Service
apiVersion: v1
metadata:
  name: {{.Values.serviceInternal.name}}
  namespace: {{.Values.namespace | default .Release.Namespace}}
  {{- if .Values.serviceInternal.annotations}}
  annotations:
{{toYaml .Values.serviceInternal.annotations | indent 4}}
  {{- end}}
  labels:
    # TODO: update this to use helm helpers and more precise selection.
    app: hadron
spec:
  type: ClusterIP
  selector:
    app: hadron
  ports:
    - name: http
      port: {{.Values.serviceInternal.port}}
      protocol: TCP
      targetPort: {{.Values.serviceInternal.targetPort}}
