---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulSet.name}}
  namespace: {{.Values.namespace | default .Release.Namespace}}
  {{- if .Values.statefulSet.annotations}}
  annotations:
{{toYaml .Values.statefulSet.annotations | indent 4}}
  {{- end}}
  labels:
    # TODO: update this to use helm helpers and more precise selection.
    app: hadron
spec:
  serviceName: {{.Values.statefulSet.serviceName}}
  replicas: {{.Values.statefulSet.replicas}}
  selector:
    matchLabels:
      app: hadron
  template:
    metadata:
      labels:
        app: hadron
    spec:
      # TODO: add service account option.
      # serviceAccountName:

      # TODO: add init containers option.

      containers:
        - name: hadron
          image: {{.Values.image.fullName}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command: ["/bin/hadrond"]
          ports:
            - containerPort: {{.Values.statefulSet.server.clientPort}}
            - containerPort: {{.Values.statefulSet.server.serverPort}}
          env:
            ## Server Config
            - name: RUST_LOG
              value: {{.Values.statefulSet.server.logging}}
            - name: CLIENT_PORT
              value: {{.Values.statefulSet.server.clientPort | quote}}
            - name: SERVER_PORT
              value: {{.Values.statefulSet.server.serverPort | quote}}

            ## Raft Config
            - name: RAFT_HEARTBEAT_INTERVAL_MILLIS
              value: {{.Values.statefulSet.raft.heartbeatIntervalMillis | quote}}
            - name: RAFT_ELECTION_TIMEOUT_MAX
              value: {{.Values.statefulSet.raft.electionTimeoutMax| quote}}
            - name: RAFT_ELECTION_TIMEOUT_MIN
              value: {{.Values.statefulSet.raft.electionTimeoutMin| quote}}

            ## Storage Config
            - name: STORAGE_DATA_PATH
              value: {{.Values.statefulSet.storage.dbPath}}

            ## Clustering Config
            - name: INITIAL_CLUSTER_FORMATION_DELAY
              value: {{.Values.statefulSet.clustering.formationDelaySeconds | quote}}
            - name: DISCOVERY_BACKEND
              value: {{.Values.statefulSet.clustering.discoveryBackend}}
            - name: DISCOVERY_DNS_NAME
              value: {{.Values.statefulSet.clustering.dnsName | quote}}

            ## Client Config
            - name: CLIENT_LIVENESS_THRESHOLD
              value: {{.Values.statefulSet.client.livenessThreshold | quote}}

          volumeMounts:
            - name: data
              mountPath: {{.Values.statefulSet.storage.dbPath}}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
{{toYaml .Values.statefulSet.volume.accessModes | indent 10}}
        storageClassName: {{.Values.statefulSet.volume.storageClassName | quote}}
        resources:
          requests:
            storage: {{.Values.statefulSet.volume.volumeSize}}
