---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulSet.name}}
  namespace: {{.Values.namespace | default .Release.Namespace}}
  {{- if .Values.statefulSet.annotations}}
  annotations:
{{toYaml .Values.statefulSet.annotations | indent 4}}
  {{- end}}
  labels:
    # TODO: update this to use helm helpers and more precise selection.
    app: railgun
spec:
  serviceName: {{.Values.statefulSet.serviceName}}
  replicas: {{.Values.statefulSet.replicas}}
  selector:
    matchLabels:
      app: railgun
  template:
    metadata:
      labels:
        app: railgun
    spec:
      # TODO: add service account option.
      # serviceAccountName:

      # TODO: add init containers option.

      containers:
        - name: railgun
          image: railgun:latest
          imagePullPolicy: Never
          command: ["/bin/railgun"]
          ports:
            - containerPort: {{.Values.statefulSet.server.port}}
          env:
            ## Server Config
            - name: RG_LOGGING
              value: {{.Values.statefulSet.server.logging}}
            - name: RG_PORT
              value: {{.Values.statefulSet.server.port | quote}}

            ## Raft Config
            - name: RG_RAFT_HEARTBEAT_INTERVAL_MILLIS
              value: {{.Values.statefulSet.raft.heartbeatIntervalMillis | quote}}
            - name: RG_RAFT_ELECTION_TIMEOUT_MAX
              value: {{.Values.statefulSet.raft.electionTimeoutMax| quote}}
            - name: RG_RAFT_ELECTION_TIMEOUT_MIN
              value: {{.Values.statefulSet.raft.electionTimeoutMin| quote}}

            ## Storage Config
            - name: RG_STORAGE_DB_PATH
              value: {{.Values.statefulSet.storage.dbPath}}
            - name: RG_STORAGE_SNAPSHOT_DIR
              value: {{.Values.statefulSet.storage.snapshotDir}}

            ## Clustering Config
            - name: RG_INITIAL_CLUSTER_FORMATION_DELAY
              value: {{.Values.statefulSet.clustering.formationDelaySeconds | quote}}
            - name: RG_DISCOVERY_BACKEND
              value: {{.Values.statefulSet.clustering.discoveryBackend}}
            - name: RG_DISCOVERY_DNS_NAME
              value: {{.Values.statefulSet.clustering.dnsName | quote}}

            ## Client Config
            - name: RG_CLIENT_LIVENESS_THRESHOLD
              value: {{.Values.statefulSet.client.livenessThreshold | quote}}

          volumeMounts:
            - name: data
              mountPath: {{.Values.statefulSet.storage.dbPath}}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
{{toYaml .Values.statefulSet.volume.accessModes | indent 10}}
        storageClassName: {{.Values.statefulSet.volume.storageClassName | quote}}
        resources:
          requests:
            storage: {{.Values.statefulSet.volume.volumeSize}}
