---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.statefulSet.name}}
  namespace: {{.Values.namespace | default .Release.Namespace}}
  {{- if .Values.statefulSet.annotations}}
  annotations:
{{toYaml .Values.statefulSet.annotations | indent 4}}
  {{- end}}
  labels:
    # TODO: update this to use helm helpers and more precise selection.
    app: railgun
spec:
  serviceName: {{.Values.statefulSet.serviceName}}
  replicas: {{.Values.statefulSet.replicas}}
  selector:
    matchLabels:
      app: railgun
  template:
    metadata:
      labels:
        app: railgun
    spec:
      # TODO: add service account option.
      # serviceAccountName:

      # TODO: add init containers option.

      containers:
        - name: railgun
          image: railgun:latest
          imagePullPolicy: Never
          ports:
            - containerPort: {{.Values.statefulSet.pod.port}}
          env:
            - name: RUST_LOG
              value: railgun=debug,actix_raft=debug
            - name: RG_PORT
              value: {{.Values.statefulSet.pod.port | quote}}
            - name: RG_INITIAL_CLUSTER_FORMATION_DELAY
              value: {{.Values.statefulSet.clustering.formationDelaySeconds | quote}}
            - name: RG_DISCOVERY_BACKEND
              value: {{.Values.statefulSet.clustering.discoveryBackend}}
            - name: RG_DISCOVERY_DNS_NAME
              value: {{.Values.statefulSet.clustering.dnsName | quote}}
            - name: RG_DB_PATH
              value: {{.Values.statefulSet.db.path}}
            - name: RG_DB_PATH
              value: {{.Values.statefulSet.db.path}}

          volumeMounts:
            - name: data
              mountPath: {{.Values.statefulSet.db.path}}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
{{toYaml .Values.statefulSet.db.accessModes | indent 10}}
        storageClassName: {{.Values.statefulSet.db.storageClassName | quote}}
        resources:
          requests:
            storage: {{.Values.statefulSet.db.volumeSize}}
