[book]
authors = ["Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"]
language = "en"
multilingual = false
src = "guide/src"
title = "Hadron | Distributed event streaming, event orchestration & messaging platform"
description = "The Hadron user guide."

[build]
build-dir = "guide/book"
create-missing = false
