[package]
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"
name = "railgun"
version = "0.1.0"

[dependencies]
actix = "0.8"
chrono = "0.4"
env_logger = "0.6"
futures = "0.1"
log = "0.4"
raft = "0.5"
regex = "1"
sled = "0.23"
tokio = "0.1"
tokio-timer = "0.2"
trust-dns-resolver = "0.11"
