unstable_features = true
edition = "2018"

comment_width = 100
fn_args_layout = "Compressed"
max_width = 150
use_small_heuristics = "Default"
use_try_shorthand = true

# pre-unstable
chain_width = 75
single_line_if_else_max_width = 75
space_around_attr_eq = false
struct_lit_width = 50

# unstable
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = false
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
struct_lit_single_line = true
trailing_comma = "Vertical"
use_field_init_shorthand = true
wrap_comments = true
