---
# The ServiceAccount used by the Hadron Operator pods.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadron-operator
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    hadron.rs/component: hadron-operator-service-account
    {{- include "chart.labels" . | indent 4 }}

---
# The ServiceAccount used by the Hadron Stream pods.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadron-stream
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    hadron.rs/component: hadron-stream-service-account
    {{- include "chart.labels" . | indent 4 }}
