# NOTE WELL: this Dockerfile assumes a context from the root of this repo.
FROM debian:stretch-slim
ARG ARTIFACT_PATH="./target/.artifacts/hadron"
COPY ${ARTIFACT_PATH} /bin/hadron
CMD ["/bin/hadron"]
