[package]
name = "core"
version = "0.1.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
env_logger = "0.6"
log = "0.4"
raft = "0.5"
regex = "1"
sled = "0.23"
