## The service which will be used by clients for communicating with the Hadron cluster.
service:
  name: hadron
  annotations: {}
  port: 7000
  targetPort: 7000

## The service which the Hadron cluster itself uses for internal communication.
serviceInternal:
  name: hadron-internal
  annotations: {}
  port: 7001
  targetPort: 7001

statefulSet:
  name: hadron

  serviceName: hadron
  replicas: 5

  image:
    fullName: docker.io/hadron-project/hadron:latest
    pullPolicy: IfNotPresent

  pod:
    annotations: {}

  ## Server Config
  server:
    ## Logging configuration.
    logging: "error,hadrond=trace"
    ## The port which client network traffic is to use.
    clientPort: 7000
    ## The port which cluster internal network traffic is to use.
    serverPort: 7001

  ## Raft Config
  raft:
    ## The rate at which the Raft leader will send heartbeats in milliseconds.
    heartbeatIntervalMillis: 400
    ## The maximum amount of time for a Raft node to wait before triggering an election.
    electionTimeoutMax: 1800
    ## The minimum amount of time for a Raft node to wait before triggering an election.
    electionTimeoutMin: 900


  ## Storage Config
  storage:
    ## The path where the persistent volume for data storage will be mounted.
    dbPath: /usr/local/hadron/data

  ## Volume Config
  volume:
    ## The size of the persistent volume to provision for data storage.
    volumeSize: 5Gi
    ## The name of the storage class to use.
    ##
    ## NOTE: create your own storage class using your K8s storage provisioner,
    ## and overwrite this value.
    storageClassName: "standard"
    ## The access modes for the persistent volume for data storage.
    accessModes: [ "ReadWriteOnce" ]

  ## Cluster Config
  clustering:
    ## The number of seconds to delay before issuing an initial cluster formation command.
    ## TODO: set this value lower once dynamic cluster membership is done.
    formationDelaySeconds: 60
    ## The discovery backend to use.
    discoveryBackend: DNS
    ## The DNS name to use for service discovery.
    dnsName: "*.hadron-internal.default.svc.cluster.local."
    ## The interval in seconds which the DNS backend will poll for DNS updates.
    dnsInterval: 5

  ## Client Config
  client:
    ## The threshold in seconds of not receiving a heartbeat from a client, after which it is reckoned to be dead.
    livenessThreshold: 10
