apiVersion: hadron.rs/v1beta1
kind: Stream
metadata:
  name: events
  namespace: default
spec:
  partitions: 3
  ttl: 0
  debug: true
  image: "ghcr.io/hadron-project/hadron/hadron-stream:v0.1.0-beta.0"
  pvcVolumeSize: "5Gi"
  pvcAccessModes:
  - ReadWriteOnce

---
apiVersion: hadron.rs/v1beta1
kind: Pipeline
metadata:
  name: service-creation
  namespace: default
spec:
  sourceStream: events
  triggers:
    - service.created
  maxParallel: 50
  startPoint:
    location: beginning
  stages:
    - name: deploy-service

    - name: setup-billing
      dependencies: ["deploy-service"]
    - name: setup-monitoring
      dependencies: ["deploy-service"]
    - name: notify-user
      dependencies: ["deploy-service"]

    - name: cleanup
      dependencies:
        - deploy-service
        - setup-billing
        - setup-monitoring
        - notify-user

---
apiVersion: hadron.rs/v1beta1
kind: Token
metadata:
  name: hadron-full-access
  namespace: default
spec:
  all: true

---
apiVersion: hadron.rs/v1beta1
kind: Token
metadata:
  name: hadron-read-only
  namespace: default
spec:
  streams:
    pub: []
    sub: ["events"]

---
apiVersion: hadron.rs/v1beta1
kind: Token
metadata:
  name: hadron-read-write
  namespace: default
spec:
  streams:
    pub: ["events"]
    sub: ["events"]
