namespace: default

service:
  name: railgun
  annotations: {}
  port: 15000
  targetPort: 15000

statefulSet:
  name: railgun

  serviceName: railgun
  replicas: 3

  pod:
    annotations: {}
    port: 15000

  ## Database Configuration
  db:
    ## The path where the persistent volume for data storage will be mounted. This value is also
    ## used for the Railgun `RG_DB_PATH` env var.
    path: /var/lib/railgun/data
    ## The size of the persistent volume to provision for data storage.
    volumeSize: 5Gi
    ## The name of the storage class to use.
    storageClassName: "standard"
    ## The access modes for the persistent volume for data storage.
    accessModes: [ "ReadWriteOnce" ]
