[book]
authors = ["Anthony Dodd <Dodd.AnthonyJosiah@gmail.com>"]
language = "en"
multilingual = false
src = "src"
title = "Hadron | event streaming, workflow orchestration & messaging"
description = "The Hadron user guide."

[build]
build-dir = "book"
create-missing = false
