## Required values:
## {{ required "required value .Values.container.image.repo" .Values.container.image.repo }}
## {{ required "required value .Values.container.image.tag" .Values.container.image.tag }}
## {{ required "required value .Values.container.clientPort" .Values.container.clientPort }}
## {{ required "required value .Values.container.httpPort" .Values.container.httpPort }}
## {{ required "required value .Values.container.env.logging" .Values.container.env.logging }}
## {{ required "required value .Values.container.env.lease.durationSeconds" .Values.container.env.lease.durationSeconds }}
## {{ required "required value .Values.container.env.lease.renewSeconds" .Values.container.env.lease.renewSeconds }}
## {{ required "required value .Values.container.env.jwt.encodingKey" .Values.container.env.jwt.encodingKey }}
## {{ required "required value .Values.container.env.jwt.decodingKey" .Values.container.env.jwt.decodingKey }}
## {{ required "required value .Values.container.env.vaw.webhookCert" .Values.container.env.vaw.webhookCert }}
## {{ required "required value .Values.container.env.vaw.webhookKey" .Values.container.env.vaw.webhookKey }}

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  name: hadron-operator
  labels:
    hadron.rs/component: operator
    {{- include "chart.labels" . | indent 4 }}
    {{- range $label, $val := .Values.deployment.labels }}
    {{ $label }}: {{ $val }}
    {{- end }}
  annotations:
    {{- range $annotation, $val := .Values.deployment.annotations }}
    {{ $annotation }}: {{ $val }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      hadron.rs/component: operator
  template:
    metadata:
      annotations:
        {{- range $annotation, $val := .Values.pod.annotations }}
        {{ $annotation }}: {{ $val }}
        {{- end }}
      labels:
        hadron.rs/component: operator
        {{- include "chart.labels" . | indent 8 }}
        {{- range $label, $val := .Values.pod.labels }}
        {{ $label }}: {{ $val }}
        {{- end }}

    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: hadron-operator
      automountServiceAccountToken: true

      imagePullSecrets: {{ .Values.pod.imagePullSecrets | toJson }}

      nodeSelector: {{ .Values.pod.nodeSelector | toJson }}
      affinity: {{ .Values.pod.affinity | toJson }}
      tolerations: {{ .Values.pod.tolerations | toJson }}
      topologySpreadConstraints: {{ .Values.pod.topologySpreadConstraints | toJson }}
      securityContext: {{ .Values.pod.securityContext | toJson }}

      containers:
        - name: hadron-operator
          image: {{ .Values.container.image.repo }}:{{ .Values.container.image.tag }}
          imagePullPolicy: {{ .Values.container.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ .Values.container.clientPort }}
            - containerPort: {{ .Values.container.httpPort }}

          env:
          - name: RUST_LOG
            value: {{ .Values.container.env.logging }}
          - name: CLIENT_PORT
            value: {{ .Values.container.clientPort | quote }}
          - name: HTTP_PORT
            value: {{ .Values.container.httpPort | quote }}

          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: "metadata.name"

          - name: LEASE_DURATION_SECONDS
            value: {{ .Values.container.env.lease.durationSeconds | quote }}
          - name: LEASE_RENEW_SECONDS
            value: {{ .Values.container.env.lease.renewSeconds | quote }}

          - name: JWT_ENCODING_KEY
{{ .Values.container.env.jwt.encodingKey | toYaml | indent 12 }}
          - name: JWT_DECODING_KEY
{{ .Values.container.env.jwt.decodingKey | toYaml | indent 12 }}

          - name: WEBHOOK_CERT
{{ .Values.container.env.vaw.webhookCert | toYaml | indent 12 }}
          - name: WEBHOOK_KEY
{{ .Values.container.env.vaw.webhookKey | toYaml | indent 12 }}

          resources: {{ .Values.container.resources | toJson }}

          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: {{ .Values.container.httpPort }}
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: {{ .Values.container.httpPort }}
            initialDelaySeconds: 10
            periodSeconds: 5
