---
# The ServiceAccount used by the Hadron Operator pods.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadron-operator
  namespace: {{.Values.namespace | default .Release.Namespace}}
  labels:
    {{- include "chart.labels" . | indent 4 }}

---
# The ServiceAccount used by the Hadron Stream pods.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadron-stream
  namespace: {{.Values.namespace | default .Release.Namespace}}
  labels:
    {{- include "chart.labels" . | indent 4 }}
