apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.cluster}}
  namespace: {{.Values.namespace | default .Release.Namespace}}
  labels:
    app: hadron
    app.kubernetes.io/name: hadron
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
