---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.cluster}}-{{.Values.zone}}
  namespace: {{.Values.namespace | default .Release.Namespace}}
  {{- if .Values.statefulSet.annotations}}
  annotations:
{{toYaml .Values.statefulSet.annotations | indent 4}}
  {{- end}}
  labels:
    hadron.rs/cluster: {{.Values.cluster}}
    hadron.rs/zone: {{.Values.zone}}
    app: hadron
    app.kubernetes.io/name: hadron
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
  {{- if .Values.statefulSet.labels}}
{{toYaml .Values.statefulSet.labels | indent 4}}
  {{- end}}
spec:
  serviceName: {{.Values.cluster}}-{{.Values.zone}}
  replicas: {{.Values.statefulSet.replicas | int }}
  updateStrategy:
    type: OnDelete
    rollingUpdate: null
  selector:
    matchLabels:
      app: hadron
      hadron.rs/cluster: {{.Values.cluster}}
      hadron.rs/zone: {{.Values.zone}}
  template:
    metadata:
      {{- if .Values.statefulSet.pod.annotations}}
      annotations:
{{toYaml .Values.statefulSet.pod.annotations | indent 8}}
      {{- end}}
      labels:
        hadron.rs/cluster: {{.Values.cluster}}
        hadron.rs/zone: {{.Values.zone}}
        app: hadron
        app.kubernetes.io/name: hadron
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        {{- if .Values.statefulSet.pod.labels}}
{{toYaml .Values.statefulSet.pod.labels | indent 8}}
        {{- end}}
    spec:
      serviceAccountName: {{.Values.cluster}}
      containers:
        - name: hadron
          image: {{.Values.image.fullName}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          command: ["/bin/hadrond"]
          ports:
            - containerPort: {{.Values.statefulSet.server.clientPort}}
            - containerPort: {{.Values.statefulSet.server.serverPort}}
          env:
            ## Server Config
            - name: RUST_LOG
              value: {{.Values.statefulSet.server.logging}}
            - name: CLIENT_PORT
              value: {{.Values.statefulSet.server.clientPort | quote}}
            - name: SERVER_PORT
              value: {{.Values.statefulSet.server.serverPort | quote}}

            ## Cluster Config
            - name: CLUSTER
              value: {{.Values.cluster | quote}}
            - name: NAMESPACE
              value: {{.Values.namespace | default .Release.Namespace}}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            ## K8s Leadership Config
            - name: LEASE_DURATION_SECONDS
              value: {{.Values.statefulSet.lease.durationSeconds | quote}}
            - name: LEASE_RENEW_SECONDS
              value: {{.Values.statefulSet.lease.renewSeconds | quote}}

            ## Storage Config
            - name: STORAGE_DATA_PATH
              value: {{.Values.statefulSet.storage.dbPath}}

            ## JWT Config
            - name: JWT_ENCODING_KEY
            {{- if .Values.statefulSet.jwt.encodingKey }}
{{ toYaml .Values.statefulSet.jwt.encodingKey | indent 14}}
            {{- else}}
            {{- required "`value` or `valueFrom` required for `statefulSet.jwt.encodingKey`" nil }}
            {{- end}}
            - name: JWT_DECODING_KEY
            {{- if .Values.statefulSet.jwt.decodingKey }}
{{ toYaml .Values.statefulSet.jwt.decodingKey | indent 14}}
            {{- else}}
            {{- required "`value` or `valueFrom` required for `statefulSet.jwt.decodingKey`" nil }}
            {{- end}}

          volumeMounts:
            - name: data
              mountPath: {{.Values.statefulSet.storage.dbPath}}

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
{{toYaml .Values.statefulSet.volume.accessModes | indent 10}}
        storageClassName: {{.Values.statefulSet.volume.storageClassName | quote}}
        resources:
          requests:
            storage: {{.Values.statefulSet.volume.volumeSize}}
