apiVersion: apps/v1
kind: Deployment
metadata:
  name: pipeline-txp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pipeline-txp
  template:
    metadata:
      labels:
        app: pipeline-txp
    spec:
      containers:
      - name: pipeline-txp
        image: ghcr.io/hadron-project/hadron/pipeline-txp:latest
        env:
        - name: RUST_LOG
          value: error,pipeline_txp=debug,hadron_client=debug
        - name: HADRON_TOKEN
          valueFrom:
            secretKeyRef:
              name: hadron-full-access
              key: token
        - name: HADRON_URL
          value: http://events.default.svc.cluster.local:7000
        - name: POSTGRES_URL
          value: postgres://postgres:password@postgres.default.svc.cluster.local:5432/postgres
