name: CI Release
on:
  workflow_call:
    inputs:
      project:
        type: string
        required: true
        description: 'The Rust project to target'
      tagPrefix:
        type: string
        required: true
        description: 'The tag prefix used to format a proper semver tag for containers'
      dir:
        type: string
        required: false
        default: '.'
        description: 'The directory to start from'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/hadron-project/hadron/${{ inputs.project }}
    steps:
    - name: Setup | Checkout
      uses: actions/checkout@v2

    - name: Setup | Git Tag
      id: git_tag
      run: echo ::set-output name=TAG::"${GITHUB_REF/refs\/tags\/${{ inputs.tagPrefix }}/}"
      shell: bash

    - name: Setup | Buildx
      uses: docker/setup-buildx-action@v1

    - name: Setup | Login ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build | Docker Deps
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dir }}/${{ inputs.project }}/Dockerfile
        target: builder
        push: true
        build-args: RELEASE_OPT=--release
        cache-from: type=registry,ref=${{ env.REGISTRY }}:deps
        cache-to: type=registry,ref=${{ env.REGISTRY }}:deps,mode=max
        tags: ${{ env.REGISTRY }}:deps

    - name: Build | Docker Release
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ inputs.dir }}/${{ inputs.project }}/Dockerfile
        target: release
        push: true
        build-args: RELEASE_OPT=--release
        cache-from: type=registry,ref=${{ env.REGISTRY }}:deps
        tags: |
          ${{ env.REGISTRY }}:${{ steps.git_tag.outputs.TAG }}
          ${{ env.REGISTRY }}:latest

    - name: Setup | Create Release Log
      run: cat ${{ inputs.dir }}/${{ inputs.project }}/CHANGELOG.md | tail -n +7 | head -n 50 > RELEASE_LOG.md

    - name: Build | Publish Pre-Release
      uses: softprops/action-gh-release@v1
      with:
        name: Hadron Stream ${{ steps.git_tag.outputs.TAG }}
        body_path: RELEASE_LOG.md
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
