name: CI Client
on:
  push:
    branches:
      - "*"
    paths:
      - "hadron-client/**"
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  ci:
    uses: hadron-project/hadron/.github/workflows/_rust-ci-base.yaml@main
    with:
      project: hadron-client
