name: CI Client
on:
  pull_request:
    branches:
      - "*"
    paths:
      - "hadron-client/**"
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  ci:
    uses: hadron-project/hadron/.github/workflows/_rust-ci.yaml@main
    with:
      project: hadron-client
