name: CI CLI
on:
  push:
    branches:
      - "*"
    paths:
      - 'hadron-cli/**'
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  ci:
    uses: hadron-project/hadron/.github/workflows/_rust-ci-base.yaml@main
    with:
      project: hadron-cli
