name: CI Core
on:
  push:
    branches:
      - "*"
    paths:
      - 'examples/**'
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  pipeline-txp:
    uses: hadron-project/hadron/.github/workflows/_rust-ci-base.yaml@main
    with:
      project: pipeline-transactional-processing
      dir: examples
  pipeline-txp:
    uses: hadron-project/hadron/.github/workflows/_rust-ci-base.yaml@main
    with:
      project: stream-transactional-processing
      dir: examples
