name: CI Operator
on:
  push:
    branches:
      - "*"
    paths:
      - 'hadron-operator/**'
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  ci:
    uses: hadron-project/hadron/.github/workflows/_rust-ci-base.yaml@99-compaction
    with:
      project: hadron-operator
