name: CI Stream
on:
  pull_request:
    branches:
      - "*"
    paths:
      - "hadron-stream/**"
      - "hadron-core/**"
      - "!**.md"
    tags-ignore:
      - "*"

jobs:
  ci:
    uses: hadron-project/hadron/.github/workflows/_rust-ci.yaml@main
    with:
      project: hadron-stream
