name: Release Operator
on:
  push:
    tags:
      - "operator-v*"

jobs:
  release:
    uses: hadron-project/hadron/.github/workflows/_rust-release.yaml@main
    with:
      project: hadron-operator
      tagPrefix: operator-
