name: Pages
on:
  push:
    branches:
      - "main"
    paths:
      - "guide/**"
      - ".github/workflows/pages.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.6'

      - name: Build
        run: mdbook build guide

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./guide/book
